---
title: Marco Ferraioli (ParanoiaSystem)
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: marcoferraioli@live.com
description: 'Hi, I''m Marco Ferraioli A.K.A. ParanoiaSystem and this is my site and
  blog.

'
baseurl: ''
url: https://paranoiasystem.github.io
twitter_username: overflowsystem
github_username: paranoiasystem
comments: true
markdown: kramdown
